spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgres
    hikari:
      schema: public
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
